title: Boutique for a Week
description: >-
  Shop Orlando's best kids consignment sale. Gently used children's clothing, toys, baby gear and more at up to 80% off retail in Casselberry, FL.
url: "https://boutiqueforaweek.com"
email: info@boutiqueforaweek.com
sale_start: "2026-04-12"
sale_stage: "04_before"
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap

pagination:
  enabled: true
  sort_reverse: true

redirect_from:
  json: false

defaults:
  -
    scope:
      path: "pages/volunteers/*"
    values:
      section: "volunteers"
      image: "/img/col_left_volunteers.webp"
      image_width: 276
      image_height: 487
  -
    scope:
      path: "pages/consignors/*"
    values:
      section: "consignors"
      image: "/img/col_left_consignors.webp"
      image_width: 260
      image_height: 515
  -
    scope:
      path: "pages/shoppers/*"
    values:
      section: "shoppers"
      image: "/img/col_left_shoppers.webp"
      image_width: 240
      image_height: 535
  -
    scope:
      path: "pages/schedule/*"
    values:
      section: "schedule"
      image: "/img/col_left_events.webp"
      image_width: 275
      image_height: 511
  -
    scope:
      path: "pages/register.md"
    values:
      section: "register"
      image: "/img/col_left_register.webp"
      image_width: 273
      image_height: 608
  -
    scope:
      path: "pages/about/*"
    values:
      section: "about"
      image: "/img/col_left_about.webp"
      image_width: 259
      image_height: 453
  -
    scope:
      path: "pages/privacy-policy.md"
    values:
      section: "about"
      image: "/img/col_left_about.webp"
      image_width: 259
      image_height: 453
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      permalink: "/blog/:year/:month/:day/:title/"
      sitemap: false
  -
    scope:
      path: ""
    values:
      layout: "default"
