title: Boutique for a Week
description: >-
  Voted Best Kids Consignment Sale in Central Florida
url: "https://boutiqueforaweek.com"
email: info@boutiqueforaweek.com
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "pages/volunteers/*"
    values:
      section: "volunteers"
      image: "/img/col_left_volunteers.png"
  -
    scope:
      path: "pages/consignors/*"
    values:
      section: "consignors"
      image: "/img/col_left_consignors.png"
  -
    scope:
      path: "pages/shoppers/*"
    values:
      section: "shoppers"
      image: "/img/col_left_shoppers.png"
  -
    scope:
      path: "pages/schedule/*"
    values:
      section: "schedule"
      image: "/img/col_left_events.png"
  -
    scope:
      path: "pages/register.md"
    values:
      section: "register"
      image: "/img/col_left_register.png"
  -
    scope:
      path: "pages/about/*"
    values:
      section: "about"
      image: "/img/col_left_about.png"
  -
    scope:
      path: "pages/privacy-policy.md"
    values:
      section: "about"
      image: "/img/col_left_about.png"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"
  -
    scope:
      path: ""
    values:
      layout: "default"
