title: Boutique for a Week
description: >-
  Voted Best Kids Consignment Sale in Central Florida
url: "https://boutiqueforaweek.com"
email: info@boutiqueforaweek.com
sale_start: "2024-04-14"
sale_stage: "02_before"
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap

pagination:
  enabled: true
  sort_reverse: true

redirect_from:
  json: false

defaults:
  -
    scope:
      path: "pages/volunteers/*"
    values:
      section: "volunteers"
      image: "/img/col_left_volunteers.png"
  -
    scope:
      path: "pages/consignors/*"
    values:
      section: "consignors"
      image: "/img/col_left_consignors.png"
  -
    scope:
      path: "pages/shoppers/*"
    values:
      section: "shoppers"
      image: "/img/col_left_shoppers.png"
  -
    scope:
      path: "pages/schedule/*"
    values:
      section: "schedule"
      image: "/img/col_left_events.png"
  -
    scope:
      path: "pages/register.md"
    values:
      section: "register"
      image: "/img/col_left_register.png"
  -
    scope:
      path: "pages/about/*"
    values:
      section: "about"
      image: "/img/col_left_about.png"
  -
    scope:
      path: "pages/privacy-policy.md"
    values:
      section: "about"
      image: "/img/col_left_about.png"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      permalink: "/blog/:year/:month/:day/:title/"
  -
    scope:
      path: ""
    values:
      layout: "default"
