name: HTML Proofer
on:
  push:
    branches: main
jobs:
  checklinks:
    name: HTMLProofer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: '3.0'
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Run gulp
        run: |
          npm install
          gulp build
      - name: HTMLProofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: "--allow-hash-href --ignore-status-codes 429,999 --ignore-urls 'https://www.barnesandnobleinc.com/our-stores-communities/summer-reading-program/, https://aidinternationalinc.org/'"
