name: HTML Proofer
on:
  push:
    branches: main
jobs:
  checklinks:
    name: HTMLProofer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - name: Run gulp
        run: |
          npm install
          gulp build
      - name: HTMLProofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: "--allow-hash-href --ignore-status-codes 429,999 --ignore-urls '/www.barnesandnobleinc.com/our-stores-communities/summer-reading-program/, /aidinternationalinc.org/, /twitter.com/'"
