name: Sale Week Updates
on:
  schedule:
    - cron: "0 7 12 4 *"  # 06_sunday
    - cron: "0 4 13 4 *"  # 07_monday
    - cron: "0 4 14 4 *"  # 08_tuesday
    - cron: "0 4 15 4 *"  # 09_wednesday
    - cron: "0 4 16 4 *"  # 10_thursday
    - cron: "0 4 17 4 *"  # 11_friday_1
    - cron: "0 21 18 4 *" # 12_friday_2
    - cron: "0 17 19 4 *" # 13_saturday
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Eleventy build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - name: Install npm packages
        run: npm ci
      - name: Sunday build
        if: github.event.schedule == '0 7 12 4 *'
        run: SALE_STAGE=06_sunday npx gulp build
      - name: Monday build
        if: github.event.schedule == '0 4 13 4 *'
        run: SALE_STAGE=07_monday npx gulp build
      - name: Tuesday build
        if: github.event.schedule == '0 4 14 4 *'
        run: SALE_STAGE=08_tuesday npx gulp build
      - name: Wednesday build
        if: github.event.schedule == '0 4 15 4 *'
        run: SALE_STAGE=09_wednesday npx gulp build
      - name: Thursday build
        if: github.event.schedule == '0 4 16 4 *'
        run: SALE_STAGE=10_thursday npx gulp build
      - name: Friday pt1 build
        if: github.event.schedule == '0 4 17 4 *'
        run: SALE_STAGE=11_friday_1 npx gulp build
      - name: Friday pt2 build
        if: github.event.schedule == '0 21 18 4 *'
        run: SALE_STAGE=12_friday_2 npx gulp build
      - name: Saturday build
        if: github.event.schedule == '0 17 19 4 *'
        run: SALE_STAGE=13_saturday npx gulp build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
