name: Spell Check
on:
  push:
    branches: main
jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - name: Run gulp
        run: |
          npm ci
          npx gulp build
      - uses: rojopolis/spellcheck-github-actions@0.60.0
        name: Check Spelling
