name: Wednesday Build
on:
  schedule:
    - cron: "0 3 29 3 *"
jobs:
  jekyll:
    name: Jekyll build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        id: bundler-cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          target_branch: 'github-pages'
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_env: 09_wednesday
